// Copyright 2019 - 2021 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import (
	"encoding/json"
	"fmt"
	"strings"
)

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// CharacteristicCombination is documented here http://hl7.org/fhir/ValueSet/characteristic-combination
type CharacteristicCombination int

const (
	CharacteristicCombinationIntersection CharacteristicCombination = iota
	CharacteristicCombinationUnion
)

func (code CharacteristicCombination) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *CharacteristicCombination) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "intersection":
		*code = CharacteristicCombinationIntersection
	case "union":
		*code = CharacteristicCombinationUnion
	default:
		return fmt.Errorf("unknown CharacteristicCombination code `%s`", s)
	}
	return nil
}
func (code CharacteristicCombination) String() string {
	return code.Code()
}
func (code CharacteristicCombination) Code() string {
	switch code {
	case CharacteristicCombinationIntersection:
		return "intersection"
	case CharacteristicCombinationUnion:
		return "union"
	}
	return "<unknown>"
}
func (code CharacteristicCombination) Display() string {
	switch code {
	case CharacteristicCombinationIntersection:
		return "intersection"
	case CharacteristicCombinationUnion:
		return "union"
	}
	return "<unknown>"
}
func (code CharacteristicCombination) Definition() string {
	switch code {
	case CharacteristicCombinationIntersection:
		return "Combine characteristics with AND."
	case CharacteristicCombinationUnion:
		return "Combine characteristics with OR."
	}
	return "<unknown>"
}
